### ISSUE TITLE
侧滑删除引发的BUG 

### ISSUE THREAD

**Issue by VainAnts** [lihangleo2/MoreAboutRecyclerView#1]
侧滑删除并点击Iem，连续删掉几条后Item点击事件会无效，Demo中的两个侧滑都试过了

**Comment by lihangleo2** [comment]
兄弟。我demo里的侧滑删除，只是弹一个toast。如果你移除里的话。记得notifyItemChange。因为remove不会去主动刷。官网说remove，其实不会。这是一个bug。如果还没有解决你的问题。请联系我QQ445442684
